# Kintsugi theme for foot
# https://github.com/metalelf0/kintsugi-nvim
#
# Include from ~/.config/foot/foot.ini:
#   include=~/path/to/extras/foot/kintsugi.ini

[colors]
alpha=1.0
background=131314
foreground=cacac2

selection-foreground=dddddd
selection-background=47464c

urls=8fa3b3

regular0=131314
regular1=b38f8f
regular2=a3be8c
regular3=ebcb8b
regular4=6c7a8a
regular5=b3a3d3
regular6=6ac6f2
regular7=dddddd

bright0=444444
bright1=d9a6a6
bright2=c3de9c
bright3=fbe4a8
bright4=8fa3b3
bright5=d3a3d3
bright6=8ac6f2
bright7=ffffff
